#!/bin/bash

USER_NAME=${USER_NAME:-linuxserver.io}

PUID=${PUID:-911}
PGID=${PGID:-911}

# [[ "$USER_NAME" != "abc" ]] && \
#     usermod -l "$USER_NAME" abc && \
#     groupmod -n "$USER_NAME" abc

useradd -u $PUID -U -d /config -s /bin/false $USER_NAME

groupmod -o -g "$PGID" "$USER_NAME"
usermod -o -u "$PUID" "$USER_NAME"


echo "
User uid:    $(id -u "$USER_NAME")
User gid:    $(id -g "$USER_NAME")
-------------------------------------
"

# chown "$USER_NAME":"$USER_NAME" /app
# chown "$USER_NAME":"$USER_NAME" /config
# chown "$USER_NAME":"$USER_NAME" /defaults
