---
- name: Remove any previous Go installation
  file:
    path: /usr/local/go
    state: absent
- name: Download the Go installer
  get_url:
    url: "{{go_url}}"
    dest: /tmp/
- name: Extract {{go_name}} into /tmp/{{go_name}}
  ansible.builtin.unarchive:
    src: /tmp/{{go_name}}
    dest: /usr/local
    remote_src: yes
- name: "Validate if a String or line is present in the file"
  lineinfile:
    path: "{{user_home}}/.profile"
    line: "export PATH=$PATH:/usr/local/go/bin"
    state: present
    backup: yes