---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
  
- name: Install Docker packages.
  package:
    name: "{{docker_packages}}"
    state: "{{ docker_packages_state }}"
  notify: restart docker
  ignore_errors: "{{ansible_check_mode}}"

- name: Install docker-compose plugin.
  package:
    name: "{{ docker_compose_package }}"
    state: "{{ docker_compose_package_state }}"
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"

- include_tasks: docker-users.yaml
  when: docker_users | length > 0